### ISSUE TITLE
Cannot set UI font

### ISSUE THREAD

**Issue by bfulop** [akiyosi/gonvim#22]
Hello,

I have this setting in my `~/.gonvim/settings.toml` file:

```toml
[editor]
# ... some settings...
# Editor font-family, font-size, linespace.
fontFamily = "Iosevka SS05"
fontsize = 15
linespace = 6
ginitvim = '''
  set guifont=Fantasque\ Sans\ Mono:h15
  set linespace=7
  if g:gonvim_running == 1
    set laststatus=0
  endif
'''
```

But no matter what I set my `guifont` to, Gonvim keeps using the `fontFamily` setting for the GUI elements (tab title, and status line).

As I recall, it worked well with the `3.0` release.
